### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [RandomInsano/axp209-rs#3]
Hello!

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by RandomInsano** [comment]
Sure! Done in #4. Sorry for the delay there.

Note that there's serious potential for damage if you expand the functionality here.

This library has aged enough that it won't build out of the box (I didn't properly pin versions in Cargo.toml). I still have about five NTC CHIP computers and an original Cubieboard in a box somewhere if you need something tested (time permitting). Pull requests welcome!

**Comment by vazhnov** [comment]
Apache v2.0 / MIT license — great!
@RandomInsano, thank you!
